package com.invenio.domain;

// Generated May 4, 2013 11:37:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FutDump generated by hbm2java
 */
@Entity
@Table(name = "FUT_DUMP")
public class FutDump implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 85085109922528832L;
	private Integer futDumpId;
	private Instrument instrument;
	private BigDecimal bookValue;
	private BigDecimal netPos;
	private BigDecimal futPrice;
	private String contract;
	private BigDecimal futSettlement;
	private BigDecimal adaptedDelta;
	private BigDecimal gammaSmt;
	private BigDecimal theta;
	private BigDecimal vega;

	public FutDump() {
	}

	public FutDump(Instrument instrument, BigDecimal bookValue,
			BigDecimal netPos, BigDecimal futPrice, String contract,
			BigDecimal futSettlement, BigDecimal adaptedDelta,
			BigDecimal gammaSmt, BigDecimal theta, BigDecimal vega) {
		this.instrument = instrument;
		this.bookValue = bookValue;
		this.netPos = netPos;
		this.futPrice = futPrice;
		this.contract = contract;
		this.futSettlement = futSettlement;
		this.adaptedDelta = adaptedDelta;
		this.gammaSmt = gammaSmt;
		this.theta = theta;
		this.vega = vega;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "fut_dump_id", unique = true, nullable = false)
	public Integer getFutDumpId() {
		return this.futDumpId;
	}

	public void setFutDumpId(Integer futDumpId) {
		this.futDumpId = futDumpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "instrument_id")
	public Instrument getInstrument() {
		return this.instrument;
	}

	public void setInstrument(Instrument instrument) {
		this.instrument = instrument;
	}

	@Column(name = "book_value", precision = 10)
	public BigDecimal getBookValue() {
		return this.bookValue;
	}

	public void setBookValue(BigDecimal bookValue) {
		this.bookValue = bookValue;
	}

	@Column(name = "net_pos", precision = 10)
	public BigDecimal getNetPos() {
		return this.netPos;
	}

	public void setNetPos(BigDecimal netPos) {
		this.netPos = netPos;
	}

	@Column(name = "fut_price", precision = 10)
	public BigDecimal getFutPrice() {
		return this.futPrice;
	}

	public void setFutPrice(BigDecimal futPrice) {
		this.futPrice = futPrice;
	}

	@Column(name = "contract", length = 200)
	public String getContract() {
		return this.contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	@Column(name = "fut_settlement", precision = 10)
	public BigDecimal getFutSettlement() {
		return this.futSettlement;
	}

	public void setFutSettlement(BigDecimal futSettlement) {
		this.futSettlement = futSettlement;
	}

	@Column(name = "adapted_delta", precision = 10)
	public BigDecimal getAdaptedDelta() {
		return this.adaptedDelta;
	}

	public void setAdaptedDelta(BigDecimal adaptedDelta) {
		this.adaptedDelta = adaptedDelta;
	}

	@Column(name = "gamma_smt", precision = 10)
	public BigDecimal getGammaSmt() {
		return this.gammaSmt;
	}

	public void setGammaSmt(BigDecimal gammaSmt) {
		this.gammaSmt = gammaSmt;
	}

	@Column(name = "theta", precision = 10)
	public BigDecimal getTheta() {
		return this.theta;
	}

	public void setTheta(BigDecimal theta) {
		this.theta = theta;
	}

	@Column(name = "vega", precision = 10)
	public BigDecimal getVega() {
		return this.vega;
	}

	public void setVega(BigDecimal vega) {
		this.vega = vega;
	}

}
