package com.invenio.domain;

// Generated Jun 19, 2012 10:18:31 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * EhrMedicalMapping generated by hbm2java
 */
@Entity
@Table(name = "invenio_user_session")
@NamedQueries (
@NamedQuery(name="findInvenioUserSessionBySessionId", query="FROM com.invenio.domain.InvenioUserSession c WHERE c.invenioUser.userid = ? and c.sessionId = ?")		
)
public class InvenioUserSession implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7298258670048151531L;
	private Integer invenioUserSessionId;
	private InvenioUser invenioUser;
	private String sessionId;
	private String randomKey;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "invenio_user_session_id", unique = true, nullable = false)
	public Integer getInvenioUserSessionId() {
		return invenioUserSessionId;
	}

	public void setInvenioUserSessionId(Integer invenioUserSessionId) {
		this.invenioUserSessionId = invenioUserSessionId;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RECORD_ID", nullable = false)
	public InvenioUser getInvenioUser() {
		return this.invenioUser;
	}

	public void setInvenioUser(InvenioUser invenioUser) {
		this.invenioUser = invenioUser;
	}
	
	@Column(name = "session_id", length = 200)
	public String getSessionId() {
		return sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}
	@Column(name = "random_key", length = 100)
	public String getRandomKey() {
		return randomKey;
	}

	public void setRandomKey(String randomKey) {
		this.randomKey = randomKey;
	}
}
