package com.invenio.domain;

// Generated Jun 19, 2012 10:18:31 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvenioUser generated by hbm2java
 */
@Entity
@Table(name = "invenio_user")
@NamedQueries (
@NamedQuery(name="findInvenioUserByUserId", query="FROM com.invenio.domain.InvenioUser u WHERE u.userid = ?")		
)
public class InvenioUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1346769006814470696L;
	private Integer recordId;
	private String userid;
	private String password;
	private String secretQuestion1;
	private String secretAnswer1;
	private String secretQuestion2;
	private String secretAnswer2;
	private String firstName;
	private String middleName;
	private String lastName;
	private String gender;
	private String activeInd;
	private Date createdTime;
	private String address1;
	private String address2;
	private Date dateOfBirth;
	private String phone;
	private String email;
	private City city;
	private String zipCode;
	private String resetProfile;
	private Date resetProfileTimestamp;
	private String resetKey;
	
	public InvenioUser() {
	}

	public InvenioUser(String userid) {
		this.userid = userid;
	}

	public InvenioUser(String userid, String firstName, String middleName,
			String lastName, String activeInd, Date createdTime) {
		this.userid = userid;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.activeInd = activeInd;
		this.createdTime = createdTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RECORD_ID", unique = true, nullable = false)
	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	@Column(name = "USERID", nullable = false, length = 50)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "FIRST_NAME", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MIDDLE_NAME", length = 50)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "LAST_NAME", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "ACTIVE_IND", length = 1)
	public String getActiveInd() {
		return this.activeInd;
	}

	public void setActiveInd(String activeInd) {
		this.activeInd = activeInd;
	}

	@Column(name = "GENDER", length = 1)
	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "address_1", nullable = true, length = 250)
	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address_2", nullable = true, length = 250)
	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "date_of_birth", nullable = true, length = 10)
	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "phone",nullable = true, length = 250)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "city_id", nullable = true)
	public City getCity() {
		return city;
	}

	public void setCity(City city) {
		this.city = city;
	}
	
	@Column(name = "email", nullable = false, length = 250)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}


	@Column(name = "zip_code", nullable = true, length = 100)
	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}
	@Column(name = "password", nullable = true, length = 200)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@Column(name = "secret_question_1", nullable = true, length = 1000)
	public String getSecretQuestion1() {
		return secretQuestion1;
	}
	public void setSecretQuestion1(String secretQuestion1) {
		this.secretQuestion1 = secretQuestion1;
	}
	@Column(name = "secret_answer_1", nullable = true, length = 1000)
	public String getSecretAnswer1() {
		return secretAnswer1;
	}
	public void setSecretAnswer1(String secretAnswer1) {
		this.secretAnswer1 = secretAnswer1;
	}
	@Column(name = "secret_question_2", nullable = true, length = 1000)
	public String getSecretQuestion2() {
		return secretQuestion2;
	}
	public void setSecretQuestion2(String secretQuestion2) {
		this.secretQuestion2 = secretQuestion2;
	}
	@Column(name = "secret_answer_2", nullable = true, length = 1000)
	public String getSecretAnswer2() {
		return secretAnswer2;
	}
	public void setSecretAnswer2(String secretAnswer2) {
		this.secretAnswer2 = secretAnswer2;
	}
	@Column(name = "reset_profile", nullable = true, length = 1)
	public String getResetProfile() {
		return resetProfile;
	}
	public void setResetProfile(String resetProfile) {
		this.resetProfile = resetProfile;
	}
	@Column(name = "reset_profile_timestamp", nullable = true, length = 10)
	public Date getResetProfileTimestamp() {
		return resetProfileTimestamp;
	}
	public void setResetProfileTimestamp(Date resetProfileTimestamp) {
		this.resetProfileTimestamp = resetProfileTimestamp;
	}
	@Column(name = "reset_key", nullable = true, length = 200)
	public String getResetKey() {
		return resetKey;
	}
	public void setResetKey(String resetKey) {
		this.resetKey = resetKey;
	}
	
}
