package com.invenio.domain;

// Generated May 4, 2013 11:37:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MUsDump generated by hbm2java
 */
@Entity
@Table(name = "M_US_DUMP")
public class MUsDump implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5282895189619062779L;
	private Integer MUsDumpId;
	private Instrument instrument;
	private String strikeCode;
	private BigDecimal marketValue;
	private BigDecimal bookValue;
	private BigDecimal marketUs;
	private BigDecimal strikePrice;
	private BigDecimal strikeTotal;
	private BigDecimal marketValCall;
	private BigDecimal marketCalPut;
	private Date optionsExpiryDate;
	private String instrumentDisplay;

	public MUsDump() {
	}

	public MUsDump(Instrument instrument, String strikeCode,
			BigDecimal marketValue, BigDecimal bookValue, BigDecimal marketUs,
			BigDecimal strikePrice, BigDecimal strikeTotal,
			BigDecimal marketValCall, BigDecimal marketCalPut,
			Date optionsExpiryDate, String instrumentDisplay) {
		this.instrument = instrument;
		this.strikeCode = strikeCode;
		this.marketValue = marketValue;
		this.bookValue = bookValue;
		this.marketUs = marketUs;
		this.strikePrice = strikePrice;
		this.strikeTotal = strikeTotal;
		this.marketValCall = marketValCall;
		this.marketCalPut = marketCalPut;
		this.optionsExpiryDate = optionsExpiryDate;
		this.instrumentDisplay = instrumentDisplay;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "m_us_dump_id", unique = true, nullable = false)
	public Integer getMUsDumpId() {
		return this.MUsDumpId;
	}

	public void setMUsDumpId(Integer MUsDumpId) {
		this.MUsDumpId = MUsDumpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "instrument_id")
	public Instrument getInstrument() {
		return this.instrument;
	}

	public void setInstrument(Instrument instrument) {
		this.instrument = instrument;
	}

	@Column(name = "strike_code", length = 200)
	public String getStrikeCode() {
		return this.strikeCode;
	}

	public void setStrikeCode(String strikeCode) {
		this.strikeCode = strikeCode;
	}

	@Column(name = "market_value", precision = 10)
	public BigDecimal getMarketValue() {
		return this.marketValue;
	}

	public void setMarketValue(BigDecimal marketValue) {
		this.marketValue = marketValue;
	}

	@Column(name = "book_value", precision = 10)
	public BigDecimal getBookValue() {
		return this.bookValue;
	}

	public void setBookValue(BigDecimal bookValue) {
		this.bookValue = bookValue;
	}

	@Column(name = "market_us", precision = 10)
	public BigDecimal getMarketUs() {
		return this.marketUs;
	}

	public void setMarketUs(BigDecimal marketUs) {
		this.marketUs = marketUs;
	}

	@Column(name = "strike_price", precision = 10)
	public BigDecimal getStrikePrice() {
		return this.strikePrice;
	}

	public void setStrikePrice(BigDecimal strikePrice) {
		this.strikePrice = strikePrice;
	}

	@Column(name = "strike_total", precision = 10)
	public BigDecimal getStrikeTotal() {
		return this.strikeTotal;
	}

	public void setStrikeTotal(BigDecimal strikeTotal) {
		this.strikeTotal = strikeTotal;
	}

	@Column(name = "market_val_call", precision = 10)
	public BigDecimal getMarketValCall() {
		return this.marketValCall;
	}

	public void setMarketValCall(BigDecimal marketValCall) {
		this.marketValCall = marketValCall;
	}

	@Column(name = "market_cal_put", precision = 10)
	public BigDecimal getMarketCalPut() {
		return this.marketCalPut;
	}

	public void setMarketCalPut(BigDecimal marketCalPut) {
		this.marketCalPut = marketCalPut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "options_expiry_date", length = 19)
	public Date getOptionsExpiryDate() {
		return this.optionsExpiryDate;
	}

	public void setOptionsExpiryDate(Date optionsExpiryDate) {
		this.optionsExpiryDate = optionsExpiryDate;
	}

	@Column(name = "instrument_display", length = 200)
	public String getInstrumentDisplay() {
		return this.instrumentDisplay;
	}

	public void setInstrumentDisplay(String instrumentDisplay) {
		this.instrumentDisplay = instrumentDisplay;
	}

}
