package com.invenio.domain;

// Generated May 4, 2013 11:37:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OptDump generated by hbm2java
 */
@Entity
@Table(name = "OPT_DUMP")
public class OptDump implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4998539424647241222L;
	private Integer optDumpId;
	private Instrument instrument;
	private Integer activeLots;
	private Integer month;
	private BigDecimal strike;
	private BigDecimal CP;
	private BigDecimal prem;
	private BigDecimal origLots;
	private String portfolio;
	private BigDecimal multiple;
	private BigDecimal lotsForPivot;
	private String counterparty;
	private String duplicated;
	private String internal;
	private String trn;
	private Date trnDate;
	private String buySell;
	private Integer initialQty;
	private String contractMaturity;
	private String callPut;
	private BigDecimal stlPrm;
	private String counterpartLabel;
	private Integer liveQty;

	public OptDump() {
	}

	public OptDump(Instrument instrument, Integer activeLots, Integer month,
			BigDecimal strike, BigDecimal CP, BigDecimal prem,
			BigDecimal origLots, String portfolio, BigDecimal multiple,
			BigDecimal lotsForPivot, String counterparty, String duplicated,
			String internal, String trn, Date trnDate, String buySell,
			Integer initialQty, String contractMaturity, String callPut,
			BigDecimal stlPrm, String counterpartLabel, Integer liveQty) {
		this.instrument = instrument;
		this.activeLots = activeLots;
		this.month = month;
		this.strike = strike;
		this.CP = CP;
		this.prem = prem;
		this.origLots = origLots;
		this.portfolio = portfolio;
		this.multiple = multiple;
		this.lotsForPivot = lotsForPivot;
		this.counterparty = counterparty;
		this.duplicated = duplicated;
		this.internal = internal;
		this.trn = trn;
		this.trnDate = trnDate;
		this.buySell = buySell;
		this.initialQty = initialQty;
		this.contractMaturity = contractMaturity;
		this.callPut = callPut;
		this.stlPrm = stlPrm;
		this.counterpartLabel = counterpartLabel;
		this.liveQty = liveQty;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "opt_dump_id", unique = true, nullable = false)
	public Integer getOptDumpId() {
		return this.optDumpId;
	}

	public void setOptDumpId(Integer optDumpId) {
		this.optDumpId = optDumpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "instrument_id")
	public Instrument getInstrument() {
		return this.instrument;
	}

	public void setInstrument(Instrument instrument) {
		this.instrument = instrument;
	}

	@Column(name = "active_lots")
	public Integer getActiveLots() {
		return this.activeLots;
	}

	public void setActiveLots(Integer activeLots) {
		this.activeLots = activeLots;
	}

	@Column(name = "month")
	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	@Column(name = "strike", precision = 10)
	public BigDecimal getStrike() {
		return this.strike;
	}

	public void setStrike(BigDecimal strike) {
		this.strike = strike;
	}

	@Column(name = "c_p", precision = 10)
	public BigDecimal getCP() {
		return this.CP;
	}

	public void setCP(BigDecimal CP) {
		this.CP = CP;
	}

	@Column(name = "prem", precision = 10)
	public BigDecimal getPrem() {
		return this.prem;
	}

	public void setPrem(BigDecimal prem) {
		this.prem = prem;
	}

	@Column(name = "orig_lots", precision = 10)
	public BigDecimal getOrigLots() {
		return this.origLots;
	}

	public void setOrigLots(BigDecimal origLots) {
		this.origLots = origLots;
	}

	@Column(name = "portfolio", length = 200)
	public String getPortfolio() {
		return this.portfolio;
	}

	public void setPortfolio(String portfolio) {
		this.portfolio = portfolio;
	}

	@Column(name = "multiple", precision = 10)
	public BigDecimal getMultiple() {
		return this.multiple;
	}

	public void setMultiple(BigDecimal multiple) {
		this.multiple = multiple;
	}

	@Column(name = "lots_for_pivot", precision = 10)
	public BigDecimal getLotsForPivot() {
		return this.lotsForPivot;
	}

	public void setLotsForPivot(BigDecimal lotsForPivot) {
		this.lotsForPivot = lotsForPivot;
	}

	@Column(name = "counterparty", length = 200)
	public String getCounterparty() {
		return this.counterparty;
	}

	public void setCounterparty(String counterparty) {
		this.counterparty = counterparty;
	}

	@Column(name = "duplicated", length = 200)
	public String getDuplicated() {
		return this.duplicated;
	}

	public void setDuplicated(String duplicated) {
		this.duplicated = duplicated;
	}

	@Column(name = "internal", length = 100)
	public String getInternal() {
		return this.internal;
	}

	public void setInternal(String internal) {
		this.internal = internal;
	}

	@Column(name = "trn", length = 200)
	public String getTrn() {
		return this.trn;
	}

	public void setTrn(String trn) {
		this.trn = trn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "trn_date", length = 19)
	public Date getTrnDate() {
		return this.trnDate;
	}

	public void setTrnDate(Date trnDate) {
		this.trnDate = trnDate;
	}

	@Column(name = "buy_sell", length = 1)
	public String getBuySell() {
		return this.buySell;
	}

	public void setBuySell(String buySell) {
		this.buySell = buySell;
	}

	@Column(name = "initial_qty")
	public Integer getInitialQty() {
		return this.initialQty;
	}

	public void setInitialQty(Integer initialQty) {
		this.initialQty = initialQty;
	}

	@Column(name = "contract_maturity", length = 200)
	public String getContractMaturity() {
		return this.contractMaturity;
	}

	public void setContractMaturity(String contractMaturity) {
		this.contractMaturity = contractMaturity;
	}

	@Column(name = "call_put", length = 1)
	public String getCallPut() {
		return this.callPut;
	}

	public void setCallPut(String callPut) {
		this.callPut = callPut;
	}

	@Column(name = "stl_prm", precision = 10)
	public BigDecimal getStlPrm() {
		return this.stlPrm;
	}

	public void setStlPrm(BigDecimal stlPrm) {
		this.stlPrm = stlPrm;
	}

	@Column(name = "counterpart_label", length = 200)
	public String getCounterpartLabel() {
		return this.counterpartLabel;
	}

	public void setCounterpartLabel(String counterpartLabel) {
		this.counterpartLabel = counterpartLabel;
	}

	@Column(name = "live_qty")
	public Integer getLiveQty() {
		return this.liveQty;
	}

	public void setLiveQty(Integer liveQty) {
		this.liveQty = liveQty;
	}

}
