package com.invenio.domain;

// Generated May 4, 2013 11:37:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VolDump generated by hbm2java
 */
@Entity
@Table(name = "VOL_DUMP")
public class VolDump implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4442678100065487354L;
	private Integer volDumpId;
	private VolSurface volSurface;
	private String product;
	private BigDecimal start;
	private BigDecimal step;
	private String extrapolate;
	private BigDecimal multiple;
	private String code;
	private String futureRef;
	private String optionsRef;
	private Date expiryDate;

	public VolDump() {
	}

	public VolDump(VolSurface volSurface, String product, BigDecimal start,
			BigDecimal step, String extrapolate, BigDecimal multiple,
			String code, String futureRef, String optionsRef, Date expiryDate) {
		this.volSurface = volSurface;
		this.product = product;
		this.start = start;
		this.step = step;
		this.extrapolate = extrapolate;
		this.multiple = multiple;
		this.code = code;
		this.futureRef = futureRef;
		this.optionsRef = optionsRef;
		this.expiryDate = expiryDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vol_dump_id", unique = true, nullable = false)
	public Integer getVolDumpId() {
		return this.volDumpId;
	}

	public void setVolDumpId(Integer volDumpId) {
		this.volDumpId = volDumpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vol_surface_id")
	public VolSurface getVolSurface() {
		return this.volSurface;
	}

	public void setVolSurface(VolSurface volSurface) {
		this.volSurface = volSurface;
	}

	@Column(name = "product", length = 200)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "start", precision = 10)
	public BigDecimal getStart() {
		return this.start;
	}

	public void setStart(BigDecimal start) {
		this.start = start;
	}

	@Column(name = "step", precision = 10)
	public BigDecimal getStep() {
		return this.step;
	}

	public void setStep(BigDecimal step) {
		this.step = step;
	}

	@Column(name = "extrapolate", length = 1)
	public String getExtrapolate() {
		return this.extrapolate;
	}

	public void setExtrapolate(String extrapolate) {
		this.extrapolate = extrapolate;
	}

	@Column(name = "multiple", precision = 10)
	public BigDecimal getMultiple() {
		return this.multiple;
	}

	public void setMultiple(BigDecimal multiple) {
		this.multiple = multiple;
	}

	@Column(name = "code", length = 200)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "future_ref", length = 200)
	public String getFutureRef() {
		return this.futureRef;
	}

	public void setFutureRef(String futureRef) {
		this.futureRef = futureRef;
	}

	@Column(name = "options_ref", length = 200)
	public String getOptionsRef() {
		return this.optionsRef;
	}

	public void setOptionsRef(String optionsRef) {
		this.optionsRef = optionsRef;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiry_date", length = 10)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

}
