package com.invenio.domain;

// Generated May 4, 2013 11:37:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VolSurface generated by hbm2java
 */
@Entity
@Table(name = "vol_surface")
@NamedQueries (
@NamedQuery(name="findVolSurfaceByType", query="FROM com.invenio.domain.VolSurface vs WHERE vs.volSurfaceType = ?")		
)
public class VolSurface implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8606664390804156320L;
	private Integer volSurfaceId;
	private String volSurfaceType;
	private Set<VolDump> volDumps = new HashSet<VolDump>(0);

	public VolSurface() {
	}

	public VolSurface(String volSurfaceType) {
		this.volSurfaceType = volSurfaceType;
	}

	public VolSurface(String volSurfaceType, Set<VolDump> volDumps) {
		this.volSurfaceType = volSurfaceType;
		this.volDumps = volDumps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vol_surface_id", unique = true, nullable = false)
	public Integer getVolSurfaceId() {
		return this.volSurfaceId;
	}

	public void setVolSurfaceId(Integer volSurfaceId) {
		this.volSurfaceId = volSurfaceId;
	}

	@Column(name = "vol_surface_type", nullable = false, length = 200)
	public String getVolSurfaceType() {
		return this.volSurfaceType;
	}

	public void setVolSurfaceType(String volSurfaceType) {
		this.volSurfaceType = volSurfaceType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "volSurface")
	public Set<VolDump> getVolDumps() {
		return this.volDumps;
	}

	public void setVolDumps(Set<VolDump> volDumps) {
		this.volDumps = volDumps;
	}

}
