package com.invenio.domain;

// Generated May 4, 2013 11:37:21 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Exchange generated by hbm2java
 */
@Entity
@Table(name = "xtraders_exchange")
public class XtradersExchange implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8606664390804156320L;
	private Integer exchangeId;
	private String exchangeName;
	private String exchangeDesc;

	public XtradersExchange() {
	}

	public XtradersExchange(Integer exchangeId) {
		this.exchangeId = exchangeId;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "xtraders_exchange_id", unique = true, nullable = false)
	public Integer getExchangeId() {
		return this.exchangeId;
	}

	public void setExchangeId(Integer exchangeId) {
		this.exchangeId = exchangeId;
	}

	@Column(name = "xtraders_exchange_name", nullable = false, length = 200)
	public String getExchangeName() {
		return this.exchangeName;
	}

	public void setExchangeName(String exchangeName) {
		this.exchangeName = exchangeName;
	}

	@Column(name = "xtraders_exchange_desc", nullable = true, length = 1000)
	public String getExchangeDesc() {
		return this.exchangeDesc;
	}

	public void setExchangeDesc(String exchangeDesc) {
		this.exchangeDesc = exchangeDesc;
	}

}
